-- CreateTable
CREATE TABLE "airports" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "country" TEXT NOT NULL DEFAULT 'India',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "airports_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "airports_code_key" ON "airports"("code");

-- Seed from the platform's original static airport reference list (apps/user/lib/airports.ts)
INSERT INTO "airports" ("id", "code", "name", "city", "country", "isActive", "createdAt", "updatedAt") VALUES
  (gen_random_uuid(), 'DEL', 'Indira Gandhi International', 'New Delhi', 'India', true, now(), now()),
  (gen_random_uuid(), 'BOM', 'Chhatrapati Shivaji Maharaj International', 'Mumbai', 'India', true, now(), now()),
  (gen_random_uuid(), 'BLR', 'Kempegowda International', 'Bengaluru', 'India', true, now(), now()),
  (gen_random_uuid(), 'MAA', 'Chennai International', 'Chennai', 'India', true, now(), now()),
  (gen_random_uuid(), 'CCU', 'Netaji Subhas Chandra Bose International', 'Kolkata', 'India', true, now(), now()),
  (gen_random_uuid(), 'HYD', 'Rajiv Gandhi International', 'Hyderabad', 'India', true, now(), now()),
  (gen_random_uuid(), 'PNQ', 'Pune Airport', 'Pune', 'India', true, now(), now()),
  (gen_random_uuid(), 'AMD', 'Sardar Vallabhbhai Patel International', 'Ahmedabad', 'India', true, now(), now()),
  (gen_random_uuid(), 'COK', 'Cochin International', 'Kochi', 'India', true, now(), now()),
  (gen_random_uuid(), 'GOI', 'Goa International', 'Goa (Dabolim)', 'India', true, now(), now()),
  (gen_random_uuid(), 'GOX', 'Manohar International', 'Goa (Mopa)', 'India', true, now(), now()),
  (gen_random_uuid(), 'JAI', 'Jaipur International', 'Jaipur', 'India', true, now(), now()),
  (gen_random_uuid(), 'LKO', 'Chaudhary Charan Singh International', 'Lucknow', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXC', 'Chandigarh International', 'Chandigarh', 'India', true, now(), now()),
  (gen_random_uuid(), 'PAT', 'Jay Prakash Narayan International', 'Patna', 'India', true, now(), now()),
  (gen_random_uuid(), 'GAU', 'Lokpriya Gopinath Bordoloi International', 'Guwahati', 'India', true, now(), now()),
  (gen_random_uuid(), 'BBI', 'Biju Patnaik International', 'Bhubaneswar', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXB', 'Bagdogra Airport', 'Bagdogra', 'India', true, now(), now()),
  (gen_random_uuid(), 'SXR', 'Sheikh ul-Alam International', 'Srinagar', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXJ', 'Jammu Airport', 'Jammu', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXA', 'Maharaja Bir Bikram Airport', 'Agartala', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXR', 'Birsa Munda Airport', 'Ranchi', 'India', true, now(), now()),
  (gen_random_uuid(), 'RPR', 'Swami Vivekananda Airport', 'Raipur', 'India', true, now(), now()),
  (gen_random_uuid(), 'IDR', 'Devi Ahilyabai Holkar Airport', 'Indore', 'India', true, now(), now()),
  (gen_random_uuid(), 'NAG', 'Dr. Babasaheb Ambedkar International', 'Nagpur', 'India', true, now(), now()),
  (gen_random_uuid(), 'VNS', 'Lal Bahadur Shastri International', 'Varanasi', 'India', true, now(), now()),
  (gen_random_uuid(), 'ATQ', 'Sri Guru Ram Dass Jee International', 'Amritsar', 'India', true, now(), now()),
  (gen_random_uuid(), 'UDR', 'Maharana Pratap Airport', 'Udaipur', 'India', true, now(), now()),
  (gen_random_uuid(), 'JDH', 'Jodhpur Airport', 'Jodhpur', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXZ', 'Veer Savarkar International', 'Port Blair', 'India', true, now(), now()),
  (gen_random_uuid(), 'TRV', 'Trivandrum International', 'Thiruvananthapuram', 'India', true, now(), now()),
  (gen_random_uuid(), 'CJB', 'Coimbatore International', 'Coimbatore', 'India', true, now(), now()),
  (gen_random_uuid(), 'VTZ', 'Visakhapatnam Airport', 'Visakhapatnam', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXM', 'Madurai Airport', 'Madurai', 'India', true, now(), now()),
  (gen_random_uuid(), 'STV', 'Surat Airport', 'Surat', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXE', 'Mangaluru International', 'Mangaluru', 'India', true, now(), now()),
  (gen_random_uuid(), 'DED', 'Jolly Grant Airport', 'Dehradun', 'India', true, now(), now()),
  (gen_random_uuid(), 'IXU', 'Chhatrapati Sambhajinagar Airport', 'Aurangabad', 'India', true, now(), now()),
  (gen_random_uuid(), 'DXB', 'Dubai International', 'Dubai', 'UAE', true, now(), now()),
  (gen_random_uuid(), 'AUH', 'Zayed International', 'Abu Dhabi', 'UAE', true, now(), now()),
  (gen_random_uuid(), 'SHJ', 'Sharjah International', 'Sharjah', 'UAE', true, now(), now()),
  (gen_random_uuid(), 'DOH', 'Hamad International', 'Doha', 'Qatar', true, now(), now()),
  (gen_random_uuid(), 'SIN', 'Changi Airport', 'Singapore', 'Singapore', true, now(), now()),
  (gen_random_uuid(), 'KUL', 'Kuala Lumpur International', 'Kuala Lumpur', 'Malaysia', true, now(), now()),
  (gen_random_uuid(), 'BKK', 'Suvarnabhumi Airport', 'Bangkok', 'Thailand', true, now(), now()),
  (gen_random_uuid(), 'CMB', 'Bandaranaike International', 'Colombo', 'Sri Lanka', true, now(), now()),
  (gen_random_uuid(), 'KTM', 'Tribhuvan International', 'Kathmandu', 'Nepal', true, now(), now()),
  (gen_random_uuid(), 'DAC', 'Hazrat Shahjalal International', 'Dhaka', 'Bangladesh', true, now(), now()),
  (gen_random_uuid(), 'LHR', 'Heathrow Airport', 'London', 'United Kingdom', true, now(), now()),
  (gen_random_uuid(), 'LGW', 'Gatwick Airport', 'London', 'United Kingdom', true, now(), now()),
  (gen_random_uuid(), 'JFK', 'John F. Kennedy International', 'New York', 'USA', true, now(), now()),
  (gen_random_uuid(), 'EWR', 'Newark Liberty International', 'Newark', 'USA', true, now(), now()),
  (gen_random_uuid(), 'ORD', 'O''Hare International', 'Chicago', 'USA', true, now(), now()),
  (gen_random_uuid(), 'SFO', 'San Francisco International', 'San Francisco', 'USA', true, now(), now()),
  (gen_random_uuid(), 'YYZ', 'Toronto Pearson International', 'Toronto', 'Canada', true, now(), now()),
  (gen_random_uuid(), 'YVR', 'Vancouver International', 'Vancouver', 'Canada', true, now(), now()),
  (gen_random_uuid(), 'FRA', 'Frankfurt Airport', 'Frankfurt', 'Germany', true, now(), now()),
  (gen_random_uuid(), 'MUC', 'Munich Airport', 'Munich', 'Germany', true, now(), now()),
  (gen_random_uuid(), 'CDG', 'Charles de Gaulle Airport', 'Paris', 'France', true, now(), now()),
  (gen_random_uuid(), 'AMS', 'Schiphol Airport', 'Amsterdam', 'Netherlands', true, now(), now()),
  (gen_random_uuid(), 'IST', 'Istanbul Airport', 'Istanbul', 'Turkey', true, now(), now()),
  (gen_random_uuid(), 'SYD', 'Sydney Kingsford Smith', 'Sydney', 'Australia', true, now(), now()),
  (gen_random_uuid(), 'MEL', 'Melbourne Airport', 'Melbourne', 'Australia', true, now(), now()),
  (gen_random_uuid(), 'HKG', 'Hong Kong International', 'Hong Kong', 'Hong Kong', true, now(), now()),
  (gen_random_uuid(), 'NRT', 'Narita International', 'Tokyo', 'Japan', true, now(), now()),
  (gen_random_uuid(), 'MLE', 'Velana International', 'Male', 'Maldives', true, now(), now()),
  (gen_random_uuid(), 'JED', 'King Abdulaziz International', 'Jeddah', 'Saudi Arabia', true, now(), now()),
  (gen_random_uuid(), 'RUH', 'King Khalid International', 'Riyadh', 'Saudi Arabia', true, now(), now()),
  (gen_random_uuid(), 'MCT', 'Muscat International', 'Muscat', 'Oman', true, now(), now()),
  (gen_random_uuid(), 'KWI', 'Kuwait International', 'Kuwait City', 'Kuwait', true, now(), now()),
  (gen_random_uuid(), 'BAH', 'Bahrain International', 'Manama', 'Bahrain', true, now(), now())
ON CONFLICT ("code") DO NOTHING;
